### ISSUE TITLE
Couchbase build fails

### ISSUE THREAD

**Issue by tchlyah** [hipster-labs/jhipster-travis-build#2]
Newly activated Couchbase builds are failing, because a mandatory et non configurable Couchbase port (8093 : query service), is already used!

```
com.github.dockerjava.api.exception.InternalServerErrorException: 
{"message":"driver failed programming external connectivity on endpoint suspicious_poitras (d33f8477ab85fe99c048536e8d08a211a8d1dcade94532d0de9844bfe0e88b89):
Bind for 0.0.0.0:8093 failed: port is already allocated"}
```

[testcontainers-java-module-couchbase](https://github.com/differentway/testcontainers-java-module-couchbase) [travis build](https://travis-ci.org/differentway/testcontainers-java-module-couchbase) is successful! I'm not a travis expert, but maybe we need to add in **.travis.yml** : 
``` .yml
sudo: required
```

**Comment by tchlyah** [comment]
Or maybe it's just [03-docker-compose.sh](../blob/master/travis/scripts/03-docker-compose.sh) that is launching a Couchbase instance : 
``` bash
if [ -a src/main/docker/couchbase.yml ]; then
    docker-compose -f src/main/docker/couchbase.yml up -d
fi
```
To be honest, I didn't really understand what this file is for, I thought it is just testing docker-compose files in jhipster generated apps, especially that all tests start their own mocked database. But it seems that the launched docker image stays up during the whole test.

After analyzing the code, I understand that the docker images are launched for the last script file [05-run.sh](../blob/master/travis/scripts/05-run.sh), which launches a real app that needs a real DB!

So why not inverse the script files execution? I mean, [04-tests.sh](../blob/master/travis/scripts/04-tests.sh) before [05-run.sh](../blob/master/travis/scripts/05-run.sh) ?

**Comment by pascalgrimaud** [comment]
Thanks for your analyze.
I updated Travis configuration and didn't check closely because I was short in time.

I will fix it the next few hours or tomorrow, so no worry ;-)

**Comment by pascalgrimaud** [comment]
So I analyze the generated codes for Couchbase and it uses `couchbaseContainer`.
I found there is a conflict for launching tests when there is already a started Couchbase.

Currently, we can't launch a real Couchbase instance and launch tests after that (during development).

That's why the current build for Couchbase failed.

Maybe try to modify this code to change the exposed port ? 
https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/test/java/package/config/_DatabaseTestConfiguration.java#L82-L88

PS: FYI, this is my first time, I'm discovering Couchbase here

**Comment by tchlyah** [comment]
I tried to do my best, but, In Couchbase, for now, we simply can't configure some ports (8092->8095), as you can see in [differentway/testcontainers-java-module-couchbase](https://github.com/differentway/testcontainers-java-module-couchbase).

Can you please explain to me why you need to start the bases before tests? All DB are mocked in tests, so for me there is no point to start them before tests, we can start them after to execute protractor or curl tests.

**Comment by pascalgrimaud** [comment]
For Travis builds tests, we can change order and it will passed.

But I was thinking about the workflow for developper:
- open project
- code
- launch test -> it's OK
- launch Couchbase database
- start the application -> it's OK
- back to code
- launch test -> it will fail

**Comment by pascalgrimaud** [comment]
It seems you're right and we can't configure port between 8092->8095.
I will change order for letting the builds passed and we need to simply document that.

**Comment by pascalgrimaud** [comment]
it has been fixed there: https://github.com/hipster-labs/jhipster-travis-build/commit/3981ce25f7bb7edd21810fe9b35398f26b4adef9
