### ISSUE TITLE
Promote this project to the main jhipster organisation

### ISSUE THREAD

**Issue by PierreBesson** [hipster-labs/jhipster-travis-build#4]
For additional visibility the **jhipster-travis-build** project should be moved to the main organisation and the README content should be moved to generator-jhipster/README.md.
cc @pascalgrimaud @jdubois @deepu105 
This is not a WIP anymore.

**Comment by pascalgrimaud** [comment]
@PierreBesson : this is here for this main reason: in Travis organization, you can't have more than 5 builds at the same time. If we migrate it to JHipster organization, there will be more builds in queue, so more time to wait for PR / commits to master / merge etc.
As in Hipster-Labs organization, there are less active projects, so we can fully use it for these daily builds.

**Comment by PierreBesson** [comment]
Okay I guess you have thought this through already !

**Comment by deepu105** [comment]
@PierreBesson never question the Travis master :wink:
